# Generated by Django 6.0 on 2025-12-03 20:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('marketplace', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto_cr', models.IntegerField(default=1)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('FINALIZADO', 'Finalizado'), ('CANCELADO', 'Cancelado')], default='PENDIENTE', max_length=20)),
                ('fecha_inicio', models.DateTimeField(auto_now_add=True)),
                ('fecha_finalizacion', models.DateTimeField(blank=True, null=True)),
                ('oferente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transacciones_ofrecidas', to=settings.AUTH_USER_MODEL)),
                ('publication', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='marketplace.publication')),
                ('solicitante', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transacciones_solicitadas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
